### ISSUE TITLE
Hello, When the code will be published? :)

### ISSUE THREAD

**Issue by codestella** [wayne1123/code-nerf#1]
Hello, Thank you for the nice work.
I am waiting for code publishing.
Could you tell me the estimated schedule?
It would help so much.

Thanks for the good research again.

**Comment by xingyi-li** [comment]
Hi, Wayne! 
I would like to test models on Pix3D, and I want to obtain the extrinsic matrix where the origin of the world coordinate system is at the center of the object and the camera is looking at the center of object. I notice that "rot_mat" and "trans_mat" are not the "Rt" I want.

So how can I obtain extrinsic matrix given cam_position and inplane_rotation?

Best,
Xingyi
